# SPDX-License-Identifier: Apache-2.0

---
- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: grafana_loki_handler_restart | default(False)
