# SPDX-License-Identifier: Apache-2.0
---
- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: grafana_loki_handler_restart | default(False)
  become: true
  become_user: "{{ ownership_owner }}"

- name: Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: stopped
  when: grafana_loki_handler_stop | default(False)
  become: true
  become_user: "{{ ownership_owner }}"

- name: Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: absent
  when: grafana_loki_handler_absent | default(False)
  become: true
  become_user: "{{ ownership_owner }}"
