# SPDX-License-Identifier: Apache-2.0
---
- name: Loki - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: grafana_handler_restart | default(false)

- name: Loki - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: stopped
  when: grafana_handler_stop | default(false)
  run_once: true

- name: Loki - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: absent
  when: grafana_handler_absent | default(false)
  run_once: true
