# SPDX-License-Identifier: Apache-2.0
---
- name: Loki - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: restarted

- name: Loki - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: stopped

- name: Loki - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: absent
