# SPDX-License-Identifier: Apache-2.0
---
- name: Container Docker - OS {{ ansible_os_family }} Distribution {{ ansible_distribution }}
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}.yml"
