# SPDX-License-Identifier: Apache-2.0
---
# Ownership
ownership_owner: "{{ prometheus_name }}"
ownership_group: "{{ prometheus_name }}"

# Permissions Mode
permission_directory: "0755"
permission_file: "0644"

# Notifications and Service Names
notify_restart: "Restart Docker Compose"
notify_stop: "Stop Docker Compose"
notify_absent: "Remove Docker Compose"
