# SPDX-License-Identifier: Apache-2.0
---
# Ownership
prometheus_ownership_owner: "{{ prometheus_name }}"
prometheus_ownership_group: "{{ prometheus_name }}"

# Permissions Mode
prometheus_permission_directory: "0751"
prometheus_permission_file: "0644"

# Handler Flags
prometheus_handler_restart: true
prometheus_handler_stop: true
prometheus_handler_absent: true

# Notifications and Service Names
prometheus_notify_restart: Prometheus - Restart Docker Compose
prometheus_notify_stop: Prometheus - Stop Docker Compose
prometheus_notify_absent: Prometheus - Remove Docker Compose
