# SPDX-License-Identifier: Apache-2.0
---
# Ownership
prometheus_ownership_owner: "{{ prometheus_name }}"
prometheus_ownership_group: "{{ prometheus_name }}"

# Permissions Mode
prometheus_permission_directory: "0751"
prometheus_permission_file: "0644"

# Notifications
prometheus_notify_restart: Prometheus - Restart Docker Compose
prometheus_notify_stop: Prometheus - Stop Docker Compose
prometheus_notify_absent: Prometheus - Remove Docker Compose
