# SPDX-License-Identifier: Apache-2.0
---
# Ownership
grafana_ownership_owner: "{{ grafana_name }}"
grafana_ownership_group: "{{ grafana_name }}"

# Permissions Mode
grafana_permission_directory: "0754"
grafana_permission_file: "0644"

# Notifications
grafana_notify_restart: Grafana - Restart Docker Compose
grafana_notify_stop: Grafana - Stop Docker Compose
grafana_notify_absent: Grafana - Remove Docker Compose
