# SPDX-License-Identifier: Apache-2.0
---
# Ownership
ownership_owner: "root"
ownership_group: "root"

# Permissions Mode
permission_directory: "0750"
permission_file: "0640"

# Notifications and Service Names
service_docker: "docker"
service_docker_compose: "docker-compose"

notify_restart: "Restart Docker Compose"
notify_stop: "Stop Docker Compose"
notify_absent: "Remove Docker Compose"

# # Resource Constraints
# docker_memory_limit: "512m"
# docker_cpu_limit: "1.0"

# # Commands and Flags
# docker_compose_validation_cmd: "docker-compose config --quiet"
