# SPDX-License-Identifier: Apache-2.0
---
# Ownership
grafana_ownership_owner: "{{ grafana_name }}"
grafana_ownership_group: "{{ grafana_name }}"

# Permissions Mode
grafana_permission_directory: "0754"
grafana_permission_file: "0644"
