---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]
  - job_name: node_exporter
    static_configs:
      - targets: [node_exporter:9100]
  - job_name: loki
    static_configs:
      - targets: [loki:3100]
  - job_name: promtail
    static_configs:
      - targets: [promtail:9080]
  - job_name: tempo
    static_configs:
      - targets: [tempo:3200]
  - job_name: alloy
    static_configs:
      - targets: [alloy:4000]
  # - job_name: "blackbox_exporter"
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #     target:
  #       - https://prometheus.io
  #   static_configs:
  #     - targets: ["blackbox_exporter:9115"]
