# SPDX-License-Identifier: Apache-2.0
---
# Ownership
dependency_track_ownership_owner: "{{ dependency_track_name }}"
dependency_track_ownership_group: "{{ dependency_track_name }}"

# Permissions Mode
dependency_track_permission_directory: "0750"
dependency_track_permission_file: "0640"

# Handler Flags
dependency_track_handler_restart: true
dependency_track_handler_stop: true
dependency_track_handler_absent: true

# Notifications and Service Names
dependency_track_notify_restart: "Restart Docker Compose"
dependency_track_notify_stop: "Stop Docker Compose"
dependency_track_notify_absent: "Remove Docker Compose"
