$ANSIBLE_VAULT;1.1;AES256
36643939363562356135313538373732663464396664313735343061343464366265383632646239
3766316633393361393433316131336637616238376133300a343238623061613635646139353636
64336639313433313463613163323466636237616230633431336362623231623631666561366333
3966613266373061630a623736396161323732663637643164666361373963376162393162313935
65666131366434383364303236383734316430663863666265626362646366353866373130643438
37613062643730343333343130636630616333636461353266366237653835393134333764363335
61353238613864363561646135623831373031663563343261633536646665363963356265623665
38333232366261616233376365393637323936373133646531623665343837663731316266343632
37313436313365333261646536626462383935616430663234623335636463323838396437616338
63376334623032656163373532393432643966333734633062326261356265373032663332646637
36333133323733626634393735613038333761383639646631363462356663633731643163336136
33666239636662396234323933376338346163383631356531646664373033343733336364626231
33356237313733343336346366313862386531396265653234333966396464383434363662393533
35366535396638393330636531343964653438343363636262626634313338653532663938623431
30373566643634313130336239343261386135663333653338653863373766383330633535333830
61313632373162656235
