$ANSIBLE_VAULT;1.1;AES256
33626165373232666539353861346638383937343831636532383066373938363130376166623466
3366323733356666376465316237356538616235643764640a666262316438326365663135333863
34313538366630663035653736373035623363666438383766316631303239363265313633646236
3537313139393230630a363466383066613261333964303030383334356631316566623966376633
33666665333932353363613730303535613934303734633130396462646437653934613037383564
33656638366539363833376138373234313938626366326530383837613637363834316436663236
66386561646235383737663461613233393361613862353136623930616462313435643037303330
30343134313730366538613038366335393430306339316234643338373432363933353835613165
65323239646631363438333934303635356465626136303365393063383762646432666566663134
32383839636639646466373033623930383336343862383561353337393830393133613034323031
32393838353261633032376234636365366135393139636263326632356236343931633136356561
62653561666338373730366132656334303466623264396663363062323030303061396139646262
37393139323231626132363335386431626237306630663937636334613835616430633265643630
37616534646462363232366134663663363935383032323065626163633866316262336366363433
35393037373336336635343064306135326663393862303161663731326336646639363965653335
35656262653762653735646461303363346237343163383834616430653461336230313037353733
33646566306464643737376339643335616130396265653563356364323265643430333365336332
37343333613034636533633564363438386632663035316563333834663735353230366261643034
61343835376332643636636664656534363637666336393437633833303030313338333834623239
33333032303334636135663136623039343365333165633036336536333837653037633136353862
32393939383131336339343536353139333236306237626139666364303934346335623838616331
3330393430376337663166633630393331316363313034343237
