# SPDX-License-Identifier: Apache-2.0
---
- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Stop Docker
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Remove Docker
  ansible.builtin.service:
    name: docker
    state: absent
