# SPDX-License-Identifier: Apache-2.0
---
- name: Dependency-Track API Server - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: dependency_track_handler_restart | default(false)

- name: Dependency-Track API Server - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: stopped
  when: dependency_track_handler_stop | default(false)
  run_once: true

- name: Dependency-Track API Server - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: absent
  when: dependency_track_handler_absent | default(false)
  run_once: true
