# SPDX-License-Identifier: Apache-2.0
---
- name: Dependency-Track API Server - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: restarted

- name: Dependency-Track API Server - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: stopped

- name: Dependency-Track API Server - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: absent
