# SPDX-License-Identifier: Apache-2.0
---
- name: Dependency-Track Frontend - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_frontend_path }}"
    files:
      - docker-compose.yml
    state: restarted

- name: Dependency-Track Frontend - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_frontend_path }}"
    files:
      - docker-compose.yml
    state: stopped

- name: Dependency-Track Frontend - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_frontend_path }}"
    files:
      - docker-compose.yml
    state: absent
