# SPDX-License-Identifier: Apache-2.0
---
alertmanager_name: alertmanager
alertmanager_image: prom/alertmanager:latest
alertmanager_port: 9093
alertmanager_path: /etc/observability/alertmanager

alertmanager_handler_start: True
alertmanager_handler_restart: True
alertmanager_handler_stop: True
alertmanager_handler_absent: True
