# SPDX-License-Identifier: Apache-2.0
---
# Ownership
traefik_ownership_owner: "{{ traefik_name }}"
traefik_ownership_group: "{{ traefik_name }}"

# Permissions Mode
traefik_permission_directory: "0755"
traefik_permission_file: "0644"

# Notifications
traefik_notify_restart: Traefik - Restart Docker Compose
traefik_notify_stop: Traefik - Stop Docker Compose
traefik_notify_absent: Traefik - Remove Docker Compose
