# SPDX-License-Identifier: Apache-2.0
---
- name: Alertmanager - Ensure group ownership
  ansible.builtin.group:
    name: "{{ prometheus_ownership_group }}"
    state: present
    system: true

- name: Alertmanager - Ensure user ownership
  ansible.builtin.user:
    name: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    state: present

- name: Alertmanager - Securely create directories
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_alertmanager_path }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_directory }}"

- name: Alertmanager - Securely copy content
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_alertmanager_path }}/{{ item }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"
  loop:
    - config.yml

- name: Alertmanager - Securely template Jinja2 files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_alertmanager_path }}/docker-compose.yml"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"
  notify:
    - prometheus_restart

- name: Alertmanager - Deploy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    state: present

- name: Alertmanager - Destroy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - prometheus_absent

- name: Alertmanager - Restart Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - prometheus_restart

- name: Alertmanager - Stop Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - prometheus_stop
