# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure Group for Prometheus Alertmanager
  ansible.builtin.group:
    name: "{{ ownership_group }}"
    state: present
    system: yes
  become: true

- name: Ensure User for Prometheus Alertmanager
  ansible.builtin.user:
    name: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    shell: /usr/sbin/nologin
    system: yes
  become: true

- name: Securely Create Directory for Prometheus Alertmanager
  ansible.builtin.file:
    state: directory
    path: "{{ alertmanager_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Copy Content for Prometheus Alertmanager
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_path }}/{{ item }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - config.yml
  become: true

- name: Securely Template Files for Prometheus Alertmanager
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ alertmanager_path }}/docker-compose.yml"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  become: true

- name: Deploy Prometheus Alertmanager
  community.docker.docker_compose_v2:
    project_src: "{{ alertmanager_path }}"
    state: present
  become: true
  notify:
    - "{{ notify_restart }}"

- name: Stop Prometheus Alertmanager
  community.docker.docker_compose_v2:
    project_src: "{{ alertmanager_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - "{{ notify_stop }}"

- name: Destroy Prometheus Alertmanager
  community.docker.docker_compose_v2:
    project_src: "{{ alertmanager_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - "{{ notify_absent }}"
