# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Alertmanager Create Directory
  ansible.builtin.file:
    path: "{{ prometheus_alertmanager_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Prometheus Alertmanager Copy Content
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_alertmanager_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - config.yml
  become: true

- name: Prometheus Alertmanager Template Expressions
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_alertmanager_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Prometheus Alertmanager Deploy
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    state: present
  notify:
    - Restart Docker Compose