# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure Group for Prometheus Process Exporter
  ansible.builtin.group:
    name: "{{ prometheus_ownership_group }}"
    state: present
    system: true
  become: true

- name: Ensure User for Prometheus Process Exporter
  ansible.builtin.user:
    name: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    state: present
  become: true

- name: Securely Create Directory for Prometheus Process Exporter
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_process_exporter_path }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_directory }}"
  become: true

- name: Securely Copy Content for Prometheus Process Exporter
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_process_exporter_path }}/{{ item }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"
  loop:
    - config.yml
  become: true

- name: Securely Template Files for Prometheus Process Exporter
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_process_exporter_path }}/docker-compose.yml"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"
  become: true

- name: Deploy Prometheus Process Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_process_exporter_path }}"
    state: present
  become: true
  notify:
    - "{{ prometheus_notify_restart }}"

- name: Destroy Prometheus Process Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_process_exporter_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - "{{ prometheus_notify_absent }}"

- name: Restart Prometheus Process Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_process_exporter_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - "{{ prometheus_notify_restart }}"

- name: Stop Prometheus Process Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_process_exporter_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - "{{ prometheus_notify_stop }}"
