# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Process Exporter Create Directory
  ansible.builtin.file:
    path: "{{ prometheus_process_exporter_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  become: true

- name: Prometheus Process Copy Exporter Config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_process_exporter_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - config.yml
  become: true

- name: Prometheus Process Exporter Template Files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_process_exporter_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0640"
  become: true

- name: Prometheus Process Exporter Deploy
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_process_exporter_path }}"
    state: present
  notify:
    - Restart Docker Compose
