# SPDX-License-Identifier: Apache-2.0
---
- name: Securely Create Directory for Prometheus Process Exporter
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_process_exporter_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Copy Content for Prometheus Process Exporter
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_process_exporter_path }}/{{ item }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - config.yml
  become: true

- name: Prometheus Process Exporter Template Files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_process_exporter_path }}/docker-compose.yml"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  become: true

- name: Deploy Prometheus Process Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_process_exporter_path }}"
    state: present
  notify:
    - "{{ notify_restart }}"
