# SPDX-License-Identifier: Apache-2.0

---
- name: Securely Create Directory for Grafana
  ansible.builtin.file:
    state: directory
    path: "{{ grafana_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Copy Content for Grafana
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ grafana_path }}/{{ item }}/"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - dashboards
    - provisioning
  become: true
  notify:
    - "{{ notify_restart }}"

- name: Securely Template Files for Grafana
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ grafana_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - docker-compose.yml.j2
    - grafana.ini.j2
  become: true

- name: Deploy Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    state: present
  notify:
    - "{{ notify_restart }}"
