# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure Group for Grafana
  ansible.builtin.group:
    name: "{{ ownership_group }}"
    state: present
    system: yes
  become: true

- name: Ensure User for Grafana
  ansible.builtin.user:
    name: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    shell: /usr/sbin/nologin
    system: yes
  become: true

- name: Securely Create Directory for Grafana
  ansible.builtin.file:
    state: directory
    path: "{{ grafana_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Copy Content for Grafana
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ grafana_path }}/{{ item }}/"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - dashboards
    - provisioning
  become: true
  notify:
    - "{{ notify_restart }}"

- name: Securely Template Files for Grafana
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ grafana_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - docker-compose.yml.j2
    - grafana.ini.j2
  become: true

- name: Deploy Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    state: present
  become: true
  notify:
    - "{{ notify_restart }}"

- name: Destroy Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - "{{ notify_absent }}"

- name: Restart Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - "{{ notify_restart }}"

- name: Stop Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - "{{ notify_stop }}"
