# SPDX-License-Identifier: Apache-2.0
---
- name: Grafana - Ensure group ownership
  ansible.builtin.group:
    name: "{{ grafana_ownership_group }}"
    state: present
    system: true

- name: Grafana - Ensure user ownership
  ansible.builtin.user:
    name: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    state: present

- name: Grafana - Securely create directories
  ansible.builtin.file:
    state: directory
    path: "{{ grafana_path }}"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_directory }}"

- name: Grafana - Securely copy content
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ grafana_path }}/{{ item }}/"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_file }}"
  loop:
    - dashboards
    - provisioning
  notify:
    - grafana_restart

- name: Grafana - Securely template Jinja2 files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ grafana_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_file }}"
  loop:
    - docker-compose.yml.j2
    - grafana.ini.j2
  notify:
    - grafana_restart

- name: Grafana - Deploy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    state: present

- name: Grafana - Destroy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - grafana_absent

- name: Grafana - Restart Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - grafana_restart

- name: Grafana - Stop Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - grafana_stop
