# SPDX-License-Identifier: Apache-2.0
---
- name: Start Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_path }}"
    files:
      - docker-compose.yml
    state: started
  when: promtail_handler_start | default(False)

- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: promtail_handler_restart | default(False)

- name: Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_path }}"
    files:
      - docker-compose.yml
    state: stopped
  when: promtail_handler_stop | default(False)
  run_once: true

- name: Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_path }}"
    files:
      - docker-compose.yml
    state: absent
  when: promtail_handler_absent | default(False)
  run_once: true
