# SPDX-License-Identifier: Apache-2.0

---
- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: grafana_promtail_handler_restart | default(False)

- name: Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: stopped
  when: grafana_promtail_handler_stop | default(False)

- name: Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: absent
  when: grafana_promtail_handler_absent | default(False)