# SPDX-License-Identifier: Apache-2.0
---
- name: Promtail - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: restarted

- name: Promtail - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: stopped

- name: Promtail - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: absent
