# SPDX-License-Identifier: Apache-2.0
---
- name: Prometheus - Ensure group ownership
  ansible.builtin.group:
    name: "{{ prometheus_ownership_group }}"
    state: present
    system: true

- name: Prometheus - Ensure user ownership
  ansible.builtin.user:
    name: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    state: present

- name: Prometheus - Securely create directories
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_path }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_directory }}"

- name: Prometheus - Securely copy content
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_path }}/{{ item }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"
  loop:
    - prometheus.yml
    - alert-rules.yml

- name: Prometheus - Securely template Jinja2 files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_path }}/docker-compose.yml"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"
  notify:
    - prometheus_restart

- name: Prometheus - Deploy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    state: present

- name: Prometheus - Destroy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - prometheus_absent

- name: Prometheus - Restart Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - prometheus_restart

- name: Prometheus - Stop Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - prometheus_stop
