# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Create Directory
  ansible.builtin.file:
    path: "{{ prometheus_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  become: true

- name: Prometheus Copy Content
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - prometheus.yml
    - alert-rules.yml
  become: true

- name: Prometheus Template Files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0640"
  become: true

- name: Prometheus Deploy
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    state: present
  notify:
    - Restart Docker Compose