# SPDX-License-Identifier: Apache-2.0

---
- name: Securely Create Directory for Prometheus Node Exporter
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_node_exporter_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Template Files for Prometheus Node Exporter
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_node_exporter_path }}/docker-compose.yml"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  become: true

- name: Deploy Prometheus Node Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_node_exporter_path }}"
    state: present
  notify:
    - "{{ notify_restart }}"
