# SPDX-License-Identifier: Apache-2.0
---
- name: Node Exporter - Ensure group ownership
  ansible.builtin.group:
    name: "{{ prometheus_ownership_group }}"
    state: present
    system: true

- name: Node Exporter - Ensure user ownership
  ansible.builtin.user:
    name: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    state: present

- name: Node Exporter - Securely create directories
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_node_exporter_path }}"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_directory }}"

- name: Node Exporter - Securely template Jinja2 files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_node_exporter_path }}/docker-compose.yml"
    owner: "{{ prometheus_ownership_owner }}"
    group: "{{ prometheus_ownership_group }}"
    mode: "{{ prometheus_permission_file }}"

- name: Node Exporter - Deploy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_node_exporter_path }}"
    state: present
  notify:
    - "{{ prometheus_notify_restart }}"

- name: Node Exporter - Destroy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_node_exporter_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - "{{ prometheus_notify_absent }}"

- name: Node Exporter - Restart Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_node_exporter_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - "{{ prometheus_notify_restart }}"

- name: Node Exporter - Stop Containers
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_node_exporter_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - "{{ prometheus_notify_stop }}"
