# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure Group for Prometheus Node Exporter
  ansible.builtin.group:
    name: "{{ ownership_group }}"
    state: present
    system: yes
  become: true

- name: Ensure User for Prometheus Node Exporter
  ansible.builtin.user:
    name: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    shell: /usr/sbin/nologin
    system: yes
  become: true

- name: Securely Create Directory for Prometheus Node Exporter
  ansible.builtin.file:
    state: directory
    path: "{{ node_exporter_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Template Files for Prometheus Node Exporter
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ node_exporter_path }}/docker-compose.yml"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  become: true

- name: Deploy Prometheus Node Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ node_exporter_path }}"
    state: present
  become: true
  notify:
    - "{{ notify_restart }}"

- name: Stop Prometheus Node Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ node_exporter_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - "{{ notify_stop }}"

- name: Destroy Prometheus Node Exporter
  community.docker.docker_compose_v2:
    project_src: "{{ node_exporter_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - "{{ notify_absent }}"
