# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Node Exporter Create Directory
  ansible.builtin.file:
    path: "{{ prometheus_node_exporter_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Prometheus Node Exporter Template Expressions
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_node_exporter_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Prometheus Node Exporter Deploy
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_node_exporter_path }}"
    state: present
  notify:
    - Restart Docker Compose