# SPDX-License-Identifier: Apache-2.0
---
- name: Traefik - Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files:
      - docker-compose.yml
    state: restarted

- name: Traefik - Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files:
      - docker-compose.yml
    state: stopped

- name: Traefik - Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files:
      - docker-compose.yml
    state: absent
