# SPDX-License-Identifier: Apache-2.0
---
# Dependency-Track
dependency_track_name: dependency-track
dependency_track_networks:
  - dependency-track-network

# Dependency-Track Frontend (UI)
dependency_track_frontend_name: dependency-track-frontend
dependency_track_frontend_image: dependencytrack/frontend:latest
dependency_track_frontend_port: 8080
dependency_track_frontend_path: /etc/ansible_collections/component_analysis/dependency_track/frontend

dependency_track_frontend_port_expose: true
dependency_track_frontend_domain: localhost
dependency_track_frontend_labels: []
dependency_track_frontend_api_base_url: https://api.localhost
