# SPDX-License-Identifier: Apache-2.0
---
node_exporter_name: node_exporter
node_exporter_image: prom/node-exporter:latest
node_exporter_port: 9100
node_exporter_path: /etc/observability/node_exporter

node_exporter_handler_start: True
node_exporter_handler_restart: True
node_exporter_handler_stop: True
node_exporter_handler_absent: True
