# SPDX-License-Identifier: Apache-2.0
---
# Ownership
dependency_track_ownership_owner: "{{ dependency_track_apiserver_name }}"
dependency_track_ownership_group: "{{ dependency_track_apiserver_name }}"

# Permissions Mode
dependency_track_permission_directory: "0755"
dependency_track_permission_file: "0644"
