# SPDX-License-Identifier: Apache-2.0
---
# Ownership
dependency_track_ownership_owner: "{{ dependency_track_apiserver_name }}"
dependency_track_ownership_group: "{{ dependency_track_apiserver_name }}"

# Permissions Mode
dependency_track_permission_directory: "0755"
dependency_track_permission_file: "0644"

# Notifications
dependency_track_notify_restart: Dependency-Track API Server - Restart Docker Compose
dependency_track_notify_stop: Dependency-Track API Server - Stop Docker Compose
dependency_track_notify_absent: Dependency-Track API Server - Remove Docker Compose
