# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure Group for Grafana Loki
  ansible.builtin.group:
    name: "{{ grafana_ownership_group }}"
    state: present
    system: true
  become: true

- name: Ensure User for Grafana Loki
  ansible.builtin.user:
    name: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    state: present
  become: true

- name: Securely Create Directory for Grafana Loki
  ansible.builtin.file:
    state: directory
    path: "{{ grafana_loki_path }}"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_directory }}"
  become: true

- name: Securely Copy Content for Grafana Loki
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ grafana_loki_path }}/{{ item }}"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_file }}"
  loop:
    - config.yml
  become: true

- name: Securely Template Files for Grafana Loki
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_loki_path }}/docker-compose.yml"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_file }}"
  become: true

- name: Deploy Grafana Loki
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    state: present
  become: true
  notify:
    - "{{ grafana_notify_restart }}"

- name: Destroy Grafana Loki
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - "{{ grafana_notify_absent }}"

- name: Restart Grafana Loki
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - "{{ grafana_notify_restart }}"

- name: Stop Grafana Loki
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - "{{ grafana_notify_stop }}"
