# SPDX-License-Identifier: Apache-2.0

---
- name: Grafana Loki Create Directory
  ansible.builtin.file:
    path: "{{ grafana_loki_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Grafana Loki Copy Content
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ grafana_loki_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - config.yml
  become: true

- name: Grafana Loki Template Files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_loki_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Grafana Loki Deploy
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_loki_path }}"
    state: present
  notify:
    - Restart Docker Compose