# SPDX-License-Identifier: Apache-2.0
---
# Ownership
ownership_owner: "root"
ownership_group: "root"

# Permissions Mode
permission_directory: "0755"
permission_file: "0644"

# Notifications and Service Names
notify_restart: "Restart Docker Compose"
notify_stop: "Stop Docker Compose"
notify_absent: "Remove Docker Compose"
