# SPDX-License-Identifier: Apache-2.0
---
# Ownership
grafana_ownership_owner: "{{ grafana_loki_name }}"
grafana_ownership_group: "{{ grafana_loki_name }}"

# Permissions Mode
grafana_permission_directory: "0751"
grafana_permission_file: "0644"
