# SPDX-License-Identifier: Apache-2.0
---
# Ownership
grafana_ownership_owner: "{{ grafana_loki_name }}"
grafana_ownership_group: "{{ grafana_loki_name }}"

# Permissions Mode
grafana_permission_directory: "0751"
grafana_permission_file: "0644"

# Notifications
grafana_notify_restart: Loki - Restart Docker Compose
grafana_notify_stop: Loki - Stop Docker Compose
grafana_notify_absent: Loki - Remove Docker Compose
