# SPDX-License-Identifier: Apache-2.0
---
# Ownership
grafana_ownership_owner: "{{ grafana_loki_name }}"
grafana_ownership_group: "{{ grafana_loki_name }}"

# Permissions Mode
grafana_permission_directory: "0751"
grafana_permission_file: "0644"

# Handler Flags
grafana_handler_restart: true
grafana_handler_stop: true
grafana_handler_absent: true

# Notifications and Service Names
grafana_notify_restart: "Restart Docker Compose"
grafana_notify_stop: "Stop Docker Compose"
grafana_notify_absent: "Remove Docker Compose"
