$ANSIBLE_VAULT;1.1;AES256
38316365636464323631613034366466353463663965633162623730383732393263356164353062
6662633863356433316661383839363237613839393335630a613931356337633064636230633136
61383537613037666330373135356465366232613863626330373266633439313932313239396430
6465343864326534320a393237616239396531653831303463663562356433356337383365313565
62383635353233376364323762383432623365636565313364363631333961616634326362636434
32666465336365326431613238386135666566306562366262343566313264656230633661363966
61363062393333663530343665633435633139323630643732353934326162353765653231303462
65623766336466336632326432333837306439356336616363376334373261653838653932323064
31303065396236633063643435613764656632653063663838313465306531323239633239363431
65613566323738346433356365316630386334663632623561653639633833333038313933326563
63656635336663333162393061313566396366623163373563343961653666363939666630353136
64356264356434383139323032353533633239613565616338643239303630326332316235656432
30666534383334393462363233343434333730613161313162323134363965303630373133623031
35626533333634373035323038383338353964656234633232643039346163393239666163386234
62613436323839363238646565653563336436313635313139313032646366346239333837313661
61636138393233393330333538346366313466633834366632313661643264363033316361356431
65316134623238306336366663613237313266623138626138636530346233363031346561643331
31313530666436353664663030346439363731636661373539613938333130646166363166343265
613938633463636539303339663433633634
