$ANSIBLE_VAULT;1.1;AES256
34313730343865613034373837373532313362653362353532356262356265323133313764353364
3239356639366237393761623232373230326562613038660a373138376632323134333066393632
63356436363639653466663862303936346463306538313133376363363164366238313930356537
6436333265323232300a383138633663393430343136333939623337643534373335393931366661
61366239343362326630393031633331333134623630313231363735616132333232623339396635
32316265613362323065643836376139616463323365633862643963303139333333653130643231
61346434653766633138616166343835323265346138323336323536383238626562653435613638
36383864336261303134323139643337316530623732643632356131633533353934323933633461
66373062393435333163613864363564376566633165616361363333376661616262333462656334
63376232356136613963323030313434363131373366386338303935323638316435333231626434
34366233313633366437633762363337653735623864643938363135653164623164316132303039
62376239616235643639363864303932346563646239343834323935326362353431366162333030
30643537336537373636623163623134623337346634656264343436656563353262656333366631
62376463633330666232323962643930326633653130363865323336323964393630303363383164
33366361343430353632336333316465383132366239353630356165663737613465373532353161
39386365663130313130
