$ANSIBLE_VAULT;1.1;AES256
31316438393938613663383737636162656562396365316533306431393434303663323632303164
3338396330633438306637323436666365353761306561650a303632633636653966633464366535
38353830643365623061303237383536396530376535303439346336363033613430373032623165
6562653365313133300a353838633731376461623730646130353563316439663266633366393237
63623436363933303961333233333732393964336331396565626639356665656536623438333936
35626432616236333431313234346138396365383836303738663135663733306431663666393930
65643365383631303831623961653837363632343132613438383035646435353665613436326434
61356639663931626330313765376663613338383931326664386137663463383866613830363038
62383437656537613837336166666566616165626630643764346165343231393437376331326531
38373232343331633361313930323830313234356561613136353963623836333936626661656535
62626666363333363831356331633631336563653435393036363735373964343931616465366162
38383536346430636261636265616165373431336261663662633138363664316537363434633931
64646333386461356631333964353137376134313135626633613961376438356466333139613535
64326665616665393232336134646163376633656662336264303665383132343938323264656639
65643637313539383738373237663439376535353533363537363032323537386362346666656439
36656238666633336261
