# SPDX-License-Identifier: Apache-2.0
---
- name: Promtail - Ensure group ownership
  ansible.builtin.group:
    name: "{{ grafana_ownership_group }}"
    state: present
    system: true

- name: Promtail - Ensure user ownership
  ansible.builtin.user:
    name: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    state: present

- name: Promtail - Securely create directories
  ansible.builtin.file:
    state: directory
    path: "{{ grafana_promtail_path }}"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_directory }}"

- name: Promtail - Securely copy content
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ grafana_promtail_path }}/{{ item }}"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_file }}"
  loop:
    - config.yml

- name: Promtail - Securely template Jinja2 files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_promtail_path }}/docker-compose.yml"
    owner: "{{ grafana_ownership_owner }}"
    group: "{{ grafana_ownership_group }}"
    mode: "{{ grafana_permission_file }}"
  notify:
    - grafana_restart

- name: Promtail - Deploy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    state: present

- name: Promtail - Destroy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - grafana_absent

- name: Promtail - Restart Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - grafana_restart

- name: Promtail - Stop Containers
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - grafana_stop
