# SPDX-License-Identifier: Apache-2.0
---
- name: Securely Create Directory for Grafana Promtail
  ansible.builtin.file:
    state: directory
    path: "{{ grafana_promtail_path }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_directory }}"
  become: true

- name: Securely Copy Content for Grafana Promtail
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ grafana_promtail_path }}/{{ item }}"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  loop:
    - config.yml
  become: true

- name: Securely Template Files for Grafana Promtail
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_promtail_path }}/docker-compose.yml"
    owner: "{{ ownership_owner }}"
    group: "{{ ownership_group }}"
    mode: "{{ permission_file }}"
  become: true

- name: Deploy Grafana Promtail
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_promtail_path }}"
    state: present
  notify:
    - "{{ notify_restart }}"
