# SPDX-License-Identifier: Apache-2.0
---
# Ownership
prometheus_ownership_owner: "{{ prometheus_node_exporter_name }}"
prometheus_ownership_group: "{{ prometheus_node_exporter_name }}"

# Permissions Mode
prometheus_permission_directory: "0750"
prometheus_permission_file: "0640"
