# SPDX-License-Identifier: Apache-2.0
---
- name: Docker - Start service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Docker - Restart service
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Docker - Stop service
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Docker - Remove service
  ansible.builtin.service:
    name: docker
    state: absent
