# SPDX-License-Identifier: Apache-2.0
---
# Ownership
ownership_owner: "{{ process_exporter_name }}"
ownership_group: "{{ process_exporter_name }}"

# Permissions Mode
permission_directory: "0750"
permission_file: "0640"

# Notifications and Service Names
notify_start: "Start Docker Compose"
notify_restart: "Restart Docker Compose"
notify_stop: "Stop Docker Compose"
notify_absent: "Remove Docker Compose"
