# SPDX-License-Identifier: Apache-2.0
---
# Ownership
prometheus_ownership_owner: "{{ prometheus_process_exporter_name }}"
prometheus_ownership_group: "{{ prometheus_process_exporter_name }}"

# Permissions Mode
prometheus_permission_directory: "0750"
prometheus_permission_file: "0640"

# Handler Flags
prometheus_handler_restart: true
prometheus_handler_stop: true
prometheus_handler_absent: true

# Notifications and Service Names
prometheus_notify_restart: "Restart Docker Compose"
prometheus_notify_stop: "Stop Docker Compose"
prometheus_notify_absent: "Remove Docker Compose"
