# SPDX-License-Identifier: Apache-2.0
---
- name: Dependency-Track API Server - Ensure group ownership
  ansible.builtin.group:
    name: "{{ dependency_track_ownership_group }}"
    state: present
    system: true

- name: Dependency-Track API Server - Ensure user ownership
  ansible.builtin.user:
    name: "{{ dependency_track_ownership_owner }}"
    group: "{{ dependency_track_ownership_group }}"
    state: present

- name: Dependency-Track API Server - Securely create directories
  ansible.builtin.file:
    state: directory
    path: "{{ dependency_track_apiserver_path }}"
    owner: "{{ dependency_track_ownership_owner }}"
    group: "{{ dependency_track_ownership_group }}"
    mode: "{{ dependency_track_permission_directory }}"

- name: Dependency-Track API Server - Securely template Jinja2 files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ dependency_track_apiserver_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: "{{ dependency_track_ownership_owner }}"
    group: "{{ dependency_track_ownership_group }}"
    mode: "{{ dependency_track_permission_file }}"
  loop:
    - docker-compose.yml.j2
    - application.properties.j2
  notify:
    - dependency_track_restart

- name: Dependency-Track API Server - Deploy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    state: present

- name: Dependency-Track API Server - Destroy Containers
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: absent
  tags:
    - destroy
  notify:
    - dependency_track_absent

- name: Dependency-Track API Server - Restart Containers
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: restarted
  tags:
    - restart
  notify:
    - dependency_track_restart

- name: Dependency-Track API Server - Stop Containers
  community.docker.docker_compose_v2:
    project_src: "{{ dependency_track_apiserver_path }}"
    files:
      - docker-compose.yml
    state: stopped
  tags:
    - stop
  notify:
    - dependency_track_stop
