# SPDX-License-Identifier: Apache-2.0
---
- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: prometheus_alertmanager_handler_restart | default(False)

- name: Stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: stopped
  when: prometheus_alertmanager_handler_stop | default(False)

- name: Remove Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: absent
  when: prometheus_alertmanager_handler_absent | default(False)
