# SPDX-License-Identifier: Apache-2.0

---
- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_alertmanager_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when: prometheus_alertmanager_handler_restart | default(False)
