# SPDX-License-Identifier: Apache-2.0
---
- name: Prometheus - Restart Docker Compose
  listen: prometheus_restart
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    files:
      - docker-compose.yml
    state: restarted

- name: Prometheus - Stop Docker Compose
  listen: prometheus_stop
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    files:
      - docker-compose.yml
    state: stopped

- name: Prometheus - Remove Docker Compose
  listen: prometheus_absent
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_path }}"
    files:
      - docker-compose.yml
    state: absent
