# SPDX-License-Identifier: Apache-2.0
---
# Ownership
dependency_track_ownership_owner: "{{ dependency_track_frontend_name }}"
dependency_track_ownership_group: "{{ dependency_track_frontend_name }}"

# Permissions Mode
dependency_track_permission_directory: "0755"
dependency_track_permission_file: "0644"

# Handler Flags
dependency_track_handler_restart: true
dependency_track_handler_stop: true
dependency_track_handler_absent: true

# Notifications and Service Names
dependency_track_notify_restart: Dependency-Track Frontend - Restart Docker Compose
dependency_track_notify_stop: Dependency-Track Frontend - Stop Docker Compose
dependency_track_notify_absent: Dependency-Track Frontend - Remove Docker Compose
