# SPDX-License-Identifier: Apache-2.0
---
# Ports and Networking
grafana_name: grafana
grafana_image: grafana/grafana:latest
grafana_port: 3000
grafana_volume_name: grafana_data
grafana_version: "latest"

# Paths and Directories
grafana_path: /etc/grafana

# File and Template Names
compose_file: "docker-compose.yml.j2"
grafana_config_file: "grafana.ini.j2"

grafana_handler_restart: True
grafana_handler_stop: True
grafana_handler_absent: True

# Credentials (Sensitive Data - To be encrypted with Ansible Vault)
grafana_admin_user: "admin"
grafana_admin_password: "admin"
# admin_user: "{{ vault_admin_user }}"
# admin_password: "{{ vault_admin_password }}"

# Plugins
grafana_plugins:
  - grafana-clock-panel
  - grafana-piechart-panel

# Datasources
grafana_datasources:
  - name: Prometheus
    type: prometheus
    url: http://localhost:9090
    access: proxy
    is_default: true

# Dashboards
grafana_dashboards:
  - dashboard_id: 6417       # Node Exporter Full
    revision_id: 15
    datasource: Prometheus
