# SPDX-License-Identifier: Apache-2.0
---
# Observability
grafana_networks:
  - observability-network

# Grafana
grafana_name: grafana
grafana_image: grafana/grafana:latest
grafana_port: 3000
grafana_volume: grafana-data
grafana_path: /etc/ansible_collections/observability/grafana

grafana_port_expose: true
grafana_domain: observability.localhost
grafana_labels: []

# XXX Credentials Sensitive data need to be encrypted with Ansible Vault
grafana_admin_user: admin
grafana_admin_password: admin
# grafana_admin_user: "{{ vault_admin_user }}"
# grafana_admin_password: "{{ vault_admin_password }}"

# Plugins
grafana_plugins:
  - grafana-clock-panel
  - grafana-piechart-panel

# Datasources
grafana_datasources:
  - name: Prometheus
    type: prometheus
    url: http://localhost:9090
    access: proxy
    is_default: true

# Dashboards
grafana_dashboards:
  - dashboard_id: 6417 # Node Exporter Full
    revision_id: 15
    datasource: Prometheus
