# SPDX-License-Identifier: Apache-2.0
---
# Ownership
grafana_ownership_owner: "{{ grafana_promtail_name }}"
grafana_ownership_group: "{{ grafana_promtail_name }}"

# Permissions Mode
grafana_permission_directory: "0750"
grafana_permission_file: "0640"

# Notifications
grafana_notify_restart: Promtail - Restart Docker Compose
grafana_notify_stop: Promtail - Stop Docker Compose
grafana_notify_absent: Promtail - Remove Docker Compose
