# SPDX-License-Identifier: Apache-2.0
---
# Ownership
docker_ownership_owner: docker
docker_ownership_group: docker

# Permissions Mode
docker_permission_directory: "0750"
docker_permission_file: "0640"
