# SPDX-License-Identifier: Apache-2.0
---
- name: Setup Common
  hosts: local
  become: true
  roles:
    - role: sentenz.container.docker.ubuntu
  tasks:
    - name: Ensure Runs Once
      debug:
        msg: Task runs only once
      run_once: true
