# SPDX-License-Identifier: Apache-2.0
---
- name: Setup Component Analysis (Dependency-Track) with Reverse Proxy (Traefik)
  hosts: component_analysis
  become: true
  roles:
    - role: sentenz.component_analysis.dependency_track.apiserver
    - role: sentenz.component_analysis.dependency_track.frontend
    - role: sentenz.reverse_proxy.traefik
