# SPDX-License-Identifier: Apache-2.0
---
- name: Component Analysis - Setup Common
  hosts: component_analysis
  become: true
  roles:
    - role: sentenz.common.container.docker
    - role: sentenz.common.aws.ebs_volume

- name: Component Analysis - Setup Dependency-Track with Reverse Proxy (Traefik)
  hosts: component_analysis
  become: true
  roles:
    - role: sentenz.component_analysis.dependency_track.apiserver
    - role: sentenz.component_analysis.dependency_track.frontend
    - role: sentenz.reverse_proxy.traefik

# - name: Component Analysis - Setup Observability (Agents/Collectors)
#   hosts: component_analysis
#   become: true
#   roles:
#     - role: sentenz.observability.prometheus.node_exporter
#     - role: sentenz.observability.grafana.promtail
