# SPDX-License-Identifier: Apache-2.0
---
# Component Analysis (Dependency-Track)
dependency_track_apiserver_image: dependencytrack/apiserver:4.13.6
dependency_track_frontend_image: dependencytrack/frontend:4.13.6
dependency_track_database_image: postgres:alpine

# Observability (Grafana/Prometheus)
grafana_image: grafana/grafana:11.6.1
grafana_loki_image: grafana/loki:3.5.0
grafana_promtail_image: grafana/promtail:3.5.0

prometheus_image: prom/prometheus:v3.3.0
prometheus_alertmanager_image: prom/alertmanager:v0.28.1
prometheus_node_exporter_image: prom/node-exporter:v1.9.1

# Reverse Proxy (Traefik)
traefik_image: traefik:v3.5.1
