$ANSIBLE_VAULT;1.1;AES256
36666138343231613934636362616231303933616138653839336437383039393633306165356332
3163653464346439323539366461373931613363313834310a393261366661666362653766356431
63666265343765386232303635333333666231616233343538636634633636346131663462623364
3031636238333762360a326233303866643538303033356661313736393963663731636362353938
61633539393430353764313539333433303266643063363238356633343965353532626134633736
30636432643461333334353466333532633931653736303436663963613566666333653361656130
64326463313764333138363834353937623036626566336666373763646166646364336632323834
32656633393232313037363638636330333766613434336461343537626533613066316136383334
64343864313437356362373262653537633038366339623436616231653365653335353661333463
34626364326237333932613664323863393061616136643730656161346662316663613930616638
65666536643835623362376163363038333663303836343037626238303535616630616265626262
37376263666234303039383162646338353036373730383733386139643366623564653635323461
61613530366162326138383530316335306235373062306131386139346134653364323038383965
37636131646332353435653339663235386164663939393838313266656430356533303630363234
31646134373332333433393231623964623935373061363435623733626638326265383738663332
32663932316466633965613830626461613963353031383533616364306538366230366538363036
39316161633030326666303162633962326138353033356330343064356434316637636462353166
65333165323337376435633031363332346138613738373134346234636363346565643663353239
39306631303231383863656332376465383863613664643135303263646364623839393635663731
37303834356430616236623832373131363762336538623835613661383737633665656530303732
35623137333963666636616330323335346364346466653636366234303939346438
