# SPDX-License-Identifier: Apache-2.0
---
promtail_name: promtail
promtail_image: grafana/promtail:latest
promtail_port: 9080
promtail_path: /etc/observability/promtail

promtail_handler_start: True
promtail_handler_restart: True
promtail_handler_stop: True
promtail_handler_absent: True
