# SPDX-License-Identifier: Apache-2.0
---
loki_name: loki
loki_image: grafana/loki:latest
loki_port: 3100
loki_path: /etc/observability/loki

loki_handler_start: True
loki_handler_restart: True
loki_handler_stop: True
loki_handler_absent: True
